### PR TITLE
Event delegation pattern on a table chart.

### PR DESCRIPTION
**Pull request by Rehan-Khan-Engineer**
Event delegation is one of the important features of JavaScript. In this project, I have created a table chart of popular engineering branches and have applied event delegation pattern to this chart. The goal here is to highlight the element on which the user clicked without using multiple event listeners.
Live Link : https://rehan-khan-engineer.github.io/Event-delegation-table-chart/

### CODE REVIEW

**Review by syedabdullahali — APPROVED** [review]

**Review by ManSOorcode — APPROVED** [review]

**Review by OSAMA478 — APPROVED** [review]
NICE Code

**Comment by murtazshaikh** [comment]
LGTM

**Review by murtazshaikh — APPROVED** [review]
LGTM

**Review by mujeeb100 — COMMENTED** [review]
Nice!!

**Pull request merged**
